GET http://localhost:5000/ profile/
###

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "email": "something@nothing.com",
    "password": "password"
}
###
POST  http://localhost:5000/
Content-Type: application/json

{
    "email": "bakwas@bekaar.com",
    "password": "1234password"
} 
###
POST  http://localhost:5000/auth/sign-in
Content-Type: application/json

{
    "email": "kamkaro@kamaao.com",
    "password": "$$$$paisahipaisa"
}
### 

POST  http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Pranav",
    "email": "202103040@daiict.ac.in",
    "contact_no": "212173314",
    "age": 19,
    "gender": "M"
}
###